[project]
name = "iterator"
version = "0.2.0"
description = "uArchiFi iteration pipeline"
authors = [
    {name="Giorgio Fardo", email="giorgio.fardo@cea.fr"}
]
dependencies = [
    "typer",
    "rich",
]
license = { text  = "LGPL-2.1-only" }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
iterator = "tooling.iterator.runner:app"

[tool.basedpyright]
typeCheckingMode = "off"
